### ISSUE TITLE
README.md Documentation Typo

### ISSUE THREAD

**Issue by HARVS1789UK** [briceburg/silverstripe-pickerfield#6]
There is a mistake in the following line of the documentation in your README.md:

```php
$field = new HasOnePickerGridField($this, 'DamID', 'Selected Dam', $this->Dam(), 'Select a Dam');
```

It should be:

```php
new HasOnePickerField(...)
```

Otherwise you are returned an error similar to:

Fatal error: Class 'HasOnePickerGridField' not found in C:\xampp\htdocs\Kowloon\mysite\code\model\Order.php on line 77

Pretty easy to work out whats wrong here, but might trip up some people. Thanks for the good module!

**Comment by briceburg** [comment]
@HARVS1789UK can you submit this as a pull request?

**Comment by HARVS1789UK** [comment]
@briceburg Sure thing, I will do it the next time I work on the project I am using the HasOnePickerField module with, which should be in the next day or two.

**Comment by HARVS1789UK** [comment]
Sorry, only just got around to looking at this and se you have already done it :-( My bad.
